"""evalr's score configs and values are the ones artifactr's and reflexr's own mapping gave.

``score_configs.json`` was generated by running the libraries' ``scores.mapping`` (artifactr at
9c92a7f, reflexr at f91a894, the two identical but for their imports) on the types in
``feedback_types.py``: their ``ScoreConfig``s, with ``feedback_type`` named ``type_name`` as
evalr names it, and the ``score_values`` of each sample value, validated and kept as JSON as the
libraries keep feedback. Do not regenerate it from evalr: it is the libraries' behaviour that evalr
took over (ADR-0011).

The libraries create a config in Langfuse once per name and never update it, so a definition that
changed would leave the configs created before and after the change disagreeing.
"""

import json
from pathlib import Path
from typing import Any

import pytest

from evalr.core import ScoreConfig, score_configs, score_values, sync_score_configs
from evalr.memory import InMemoryScoreConfigStore

from .feedback_types import TYPES, Accuracy, Helpfulness

FIXTURE: dict[str, Any] = json.loads((Path(__file__).parent / "score_configs.json").read_text())


def test_the_fixture_covers_every_type() -> None:
    assert set(FIXTURE) == set(TYPES)


@pytest.mark.parametrize("type_name", sorted(TYPES))
def test_configs_are_the_ones_the_libraries_created(type_name: str) -> None:
    expected = tuple(
        ScoreConfig(**(config | {"categories": tuple(config["categories"])}))
        for config in FIXTURE[type_name]["configs"]
    )
    assert score_configs(TYPES[type_name], type_name=type_name) == expected


@pytest.mark.parametrize("type_name", sorted(TYPES))
def test_values_are_the_ones_the_libraries_sent(type_name: str) -> None:
    for case in FIXTURE[type_name]["values"]:
        pairs = score_values(TYPES[type_name], case["value"], type_name=type_name)
        assert [(config.name, value) for config, value in pairs] == [
            (name, value) for name, value in case["scores"]
        ]
        # The libraries' values were 1.0 and 0.0; evalr's are the bools that equal them, which a
        # Langfuse sink sends as the same numbers.
        for config, value in pairs:
            assert isinstance(value, bool) == (config.data_type == "BOOLEAN")


async def test_syncing_creates_only_the_configs_a_store_lacks() -> None:
    store = InMemoryScoreConfigStore()
    [rating, reason] = score_configs(Helpfulness)
    await store.create(rating)
    created = await sync_score_configs(
        store, [*score_configs(Helpfulness), *score_configs(Accuracy), reason]
    )
    assert created == ["helpfulness.reason", *(c.name for c in score_configs(Accuracy))]
    assert store.configs["helpfulness.rating"] is rating
    assert await sync_score_configs(store, score_configs(Accuracy)) == []


async def test_the_in_memory_store_refuses_a_name_it_has() -> None:
    store = InMemoryScoreConfigStore()
    [rating, _] = score_configs(Helpfulness)
    await store.create(rating)
    with pytest.raises(ValueError, match="exists already"):
        await store.create(rating)
